# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo/todo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftodo/todo.proto\x12\x04todo\"5\n\x08TodoItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06isDone\x18\x03 \x01(\x08\"*\n\tTodoItems\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.todo.TodoItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo.todo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TODOITEM']._serialized_start=25
  _globals['_TODOITEM']._serialized_end=78
  _globals['_TODOITEMS']._serialized_start=80
  _globals['_TODOITEMS']._serialized_end=122
# @@protoc_insertion_point(module_scope)
