[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "methodchannel"
version = "0.1.0"
description = "My minimal Python project"
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]

[tool.attacus]